# Generated by Django 6.0 on 2025-12-28 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('edad', models.PositiveBigIntegerField(verbose_name='Edad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Plan Mensual'), ('TRIMESTRAL', 'Plan Trimestral'), ('ANUAL', 'Plan Anual')], max_length=15, verbose_name='Tipo de Plan')),
                ('costo', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Costo ($)')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
